---
kind: pipeline
type: docker
name: default

steps:
  - name: yamllint
    image: sdesbure/yamllint:latest
    commands:
      - yamllint -d relaxed .drone.yml
  - name: dockerfilelint
    image: hadolint/hadolint:v1.23.0
    commands:
      - hadolint --ignore DL3008 squid5/Dockerfile
  - name: squid5
    depends_on:
      - dockerfilelint
    image: plugins/docker:19.03.8
    settings:
      dockerfile: squid5/Dockerfile
      username: hsmtkk
      password:
        from_secret: dockerhubtoken
      repo: hsmtkk/squidicap
      tags:
        - 5
