version: "3"
services:
  httpclient:
    image: hsmtkk/squidicap:httpclient
  icap4:
    image: hsmtkk/squidicap:icap
  icap5:
    image: hsmtkk/squidicap:icap
  squid4:
    image: hsmtkk/squidicap:squid4
    volumes:
      - "./squid4/squid.conf:/usr/local/squid/etc/squid.conf:ro"
  squid5:
    image: hsmtkk/squidicap:squid5
    volumes:
      - "./squid5/squid.conf:/usr/local/squid/etc/squid.conf:ro"
  nginx:
    image: nginx:1.19.7
    volumes:
      - "./nginx/html:/usr/share/nginx/html:ro"
