version: "3"
services:
  httpclient:
    image: hsmtkk/squidicap:httpclient
  icap:
    image: hsmtkk/squidicap:icap
  squid4:
    image: hsmtkk/squidicap:squid4
    volumes:
      - "./squid4/squid.conf:/usr/local/squid/etc/squid.conf:ro"
  squid5:
    image: hsmtkk/squidicap:squid5
    volumes:
      - "./squid5/squid.conf:/usr/local/squid/etc/squid.conf:ro"
  squid5etchosts:
    image: hsmtkk/squidicap:squid5etchosts
    volumes:
      - "./squid5etchosts/squid.conf:/usr/local/squid/etc/squid.conf:ro"
  squid5rawip:
    image: hsmtkk/squidicap:squid5rawip
    privileged: true
    volumes:
      - "./squid5rawip/squid.conf.tmpl:/usr/local/squid/etc/squid.conf.tmpl:ro"
  nginx:
    image: nginx:1.19.7
    volumes:
      - "./nginx/html:/usr/share/nginx/html:ro"
