version: "3"
services:
  httpclient:
    image: hsmtkk/squidicap/httpclient:latest
  icap:
    image: hsmtkk/squidicap/icap:latest
  squid4:
    image: hsmtkk/squidicap/squid:4
    volumes:
      - "./squid4/squid.conf:/usr/local/squid/etc/squid.conf:ro"
  squid5:
    image: hsmtkk/squidicap/squid:4
    volumes:
      - "./squid4/squid.conf:/usr/local/squid/etc/squid.conf:ro"
  nginx:
    image: nginx:1.19.7
    volumes:
      - "./nginx/html:/usr/share/nginx/html:ro"
